"use client";

import { motion } from "framer-motion";
import SectionWrapper from "@/components/ui/SectionWrapper";
import {
  Settings,
  Users,
  BarChart3,
  Mail,
  GitBranch,
  DollarSign,
  Heart,
  Shield,
} from "lucide-react";

const capabilities = [
  { icon: Settings, name: "Operations", desc: "Runs workflows, handles exceptions, eliminates bottlenecks." },
  { icon: Users, name: "Team", desc: "Delegates tasks, tracks progress, keeps everyone aligned." },
  { icon: BarChart3, name: "Data", desc: "Real-time dashboards, anomaly detection, instant decisions." },
  { icon: Mail, name: "Communication", desc: "Email triage, meeting prep, client correspondence." },
  { icon: GitBranch, name: "Pipeline", desc: "Sourcing, qualification, follow-ups. Nothing falls through." },
  { icon: DollarSign, name: "Finance", desc: "Invoicing, forecasting, KPI tracking. Numbers always current." },
  { icon: Heart, name: "Customers", desc: "Onboarding, retention, support. Every customer handled." },
  { icon: Shield, name: "Compliance", desc: "Regulatory monitoring, audit trails, risk management." },
];

export default function MeetMidas() {
  return (
    <SectionWrapper id="meet-midas" className="bg-surface-elevated">
      <div className="max-w-3xl mb-20">
        <motion.h2
          initial={{ opacity: 0, y: 15 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="font-[family-name:var(--font-cormorant)] text-4xl md:text-5xl font-bold text-cream mb-8"
        >
          This Is <span className="text-gold">Midas</span>
        </motion.h2>

        <div className="space-y-5 font-[family-name:var(--font-inter)] text-cream-dim text-base md:text-lg leading-relaxed font-light">
          <motion.p
            initial={{ opacity: 0, y: 10 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.1 }}
          >
            Midas is a hyper-intelligent, super-genius AI. And he&apos;s
            proudly AI. We&apos;re not going to pretend otherwise. In fact,
            that&apos;s the entire point. Everything you&apos;re reading right
            now, this website, the diagnostic you&apos;re about to take, the
            report you&apos;ll receive, all generated by Midas. This is what
            he does.
          </motion.p>
          <motion.p
            initial={{ opacity: 0, y: 10 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.2 }}
          >
            Midas is not a chatbot. Not a dashboard. Not another SaaS tool
            you&apos;ll forget about in a month. He&apos;s an AI Chief of Staff
            and an AI engineer. He doesn&apos;t just run your operations. He
            builds AI into every corner of your company. New process?
            He automates it. New problem? He builds an agent to solve it.
            He works 24/7. He never forgets. He gets smarter every single day.
          </motion.p>
          <motion.p
            initial={{ opacity: 0, y: 10 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.3 }}
            className="text-gold/90"
          >
            And when you&apos;re ready, we install him directly into your
            company. Custom name. Custom personality. Custom workflows.
            Your AI Chief of Staff, built specifically for you.
          </motion.p>
        </div>
      </div>

      <motion.h3
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        viewport={{ once: true }}
        transition={{ duration: 0.5 }}
        className="font-[family-name:var(--font-inter)] text-sm tracking-[0.2em] uppercase text-gold/50 mb-8"
      >
        What Midas Handles
      </motion.h3>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {capabilities.map((cap, i) => (
          <motion.div
            key={cap.name}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.4, delay: i * 0.06 }}
            className="bg-surface-card/80 border border-surface-border rounded-lg p-6 hover:border-gold-border/60 transition-all duration-300 group"
          >
            <cap.icon
              className="text-gold/80 mb-4 group-hover:text-gold transition-colors"
              size={26}
              strokeWidth={1.5}
            />
            <h4 className="font-[family-name:var(--font-inter)] font-semibold text-cream text-[15px] mb-2">
              {cap.name}
            </h4>
            <p className="text-cream-dim/70 text-sm leading-relaxed font-[family-name:var(--font-inter)] font-light">
              {cap.desc}
            </p>
          </motion.div>
        ))}
      </div>
    </SectionWrapper>
  );
}
